server:
  port: 8090
qiniu:
    oss:
      accessKey: CJ0RWOua0KukhT_3xuNh7Q73Ob6eLkbNtDUhQ-Dh
      secretKey: R8emp9JBEOAigmfKC2jeRX7MO3Huq-YqpzypRHgx
      bucket: lifeonline
      host: up-z2.qiniup.com
ali:
  oss:
    endPoint: oss-cn-shenzhen.aliyuncs.com
    bucketName: lifeonline
    keyId: LTAI4G2q6gv7dC7LP8jvZpd7
    keySecret: IOPQCZkFPYKp1Yjwcn1bQoOHXEGYeb
spring:
  application:
    name: service-oss
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848