qiniu:
  oss:
    accessKey: xxxxxx
    secretKey: xxxxxx
    bucket: xxxxxx
    host: xxxxxx
ali:
  oss:
    endPoint: xxxxxx
    bucketName: xxxxxx
    keyId: xxxxxx
    keySecret: xxxxxx
spring:
  application:
    name: service-oss
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848